### ISSUE TITLE
No Dart SDKs can be found

### ISSUE THREAD

**Issue by VanAnderson** [Yakiyo/dsm#28]
using `dsm install latest` or known versions like `dsm install 3.0.3` is producing an error. It seems to be pointing to a url that doesn't exist (https://storage.googleapis.com/dart-archive/channels/stable/release/3.2.6/sdk/dartsdk-darwin-x64-release.zip). Has the url scheme changed recently?

---

<img width="982" alt="image" src="https://github.com/Yakiyo/dsm/assets/16739070/e1f0158c-54b8-4ae6-8cb3-a6ead5ae0355">

---

<img width="984" alt="image" src="https://github.com/Yakiyo/dsm/assets/16739070/792145b6-9010-490a-bf14-0cf2702603ec">

**Comment by VanAnderson** [comment]
@Yakiyo I just installed `dsm` recently and I haven't gotten it to work yet, so I'm not sure if it was changed recently. I can confirm that changing the link from darwin to macos on my end gives a functioning link. Happy to help test any fixes on macos to confirm 👍

**Comment by Yakiyo** [comment]
@VanAnderson a patch fix has been released. You can try out dsm v1.0.3 and it should now work. Please let me know if it works fine or not.

**Comment by VanAnderson** [comment]
@Yakiyo works like a charm! Thanks for building this, we are lucky to have an open source tool like this!
